"""initial schema

Revision ID: 6862a82b142d
Revises: 
Create Date: 2026-07-11 01:10:58.875597

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6862a82b142d'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('houses',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'AUD'"), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_houses'))
    )
    op.create_table('users',
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('is_platform_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('balances',
    sa.Column('house_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('balance_cents', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('oldest_debt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], name=op.f('fk_balances_house_id_houses')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_balances_user_id_users')),
    sa.PrimaryKeyConstraint('house_id', 'user_id', name=op.f('pk_balances'))
    )
    op.create_table('documents',
    sa.Column('house_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('r2_key', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'uploaded', name='document_status'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], name=op.f('fk_documents_house_id_houses')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_documents_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_table('events',
    sa.Column('house_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], name=op.f('fk_events_house_id_houses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    sa.UniqueConstraint('house_id', 'seq', name=op.f('uq_events_house_id'))
    )
    op.create_table('house_invites',
    sa.Column('house_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_uses', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('use_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], name=op.f('fk_house_invites_house_id_houses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_house_invites')),
    sa.UniqueConstraint('code', name=op.f('uq_house_invites_code'))
    )
    op.create_table('house_memberships',
    sa.Column('house_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('member', 'manager', name='membership_role'), nullable=False),
    sa.Column('status', sa.Enum('active', 'left', name='membership_status'), server_default=sa.text("'active'"), nullable=False),
    sa.Column('away_days', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], name=op.f('fk_house_memberships_house_id_houses')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_house_memberships_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_house_memberships')),
    sa.UniqueConstraint('house_id', 'user_id', name=op.f('uq_house_memberships_house_id'))
    )
    op.create_table('house_seq_counters',
    sa.Column('house_id', sa.UUID(), nullable=False),
    sa.Column('next_seq', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], name=op.f('fk_house_seq_counters_house_id_houses')),
    sa.PrimaryKeyConstraint('house_id', name=op.f('pk_house_seq_counters'))
    )
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('request_hash', sa.String(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_idempotency_keys_user_id_users')),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_idempotency_keys'))
    )
    op.create_table('ledger_events',
    sa.Column('house_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('expense', 'expense_reversal', 'settlement', 'adjustment', name='ledger_event_kind'), nullable=False),
    sa.Column('ref_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_ledger_events_created_by_users')),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], name=op.f('fk_ledger_events_house_id_houses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_events'))
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('house_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], name=op.f('fk_notifications_house_id_houses')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_table('settlements',
    sa.Column('house_id', sa.UUID(), nullable=False),
    sa.Column('from_user', sa.UUID(), nullable=False),
    sa.Column('to_user', sa.UUID(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'rejected', name='settlement_status'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_user'], ['users.id'], name=op.f('fk_settlements_from_user_users')),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], name=op.f('fk_settlements_house_id_houses')),
    sa.ForeignKeyConstraint(['to_user'], ['users.id'], name=op.f('fk_settlements_to_user_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settlements'))
    )
    op.create_table('split_rules',
    sa.Column('house_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.Enum('equal', 'percentage', 'weighted', 'equal_prorated', name='split_rule_kind'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], name=op.f('fk_split_rules_house_id_houses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_split_rules'))
    )
    op.create_table('ledger_entries',
    sa.Column('ledger_event_id', sa.UUID(), nullable=False),
    sa.Column('house_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], name=op.f('fk_ledger_entries_house_id_houses')),
    sa.ForeignKeyConstraint(['ledger_event_id'], ['ledger_events.id'], name=op.f('fk_ledger_entries_ledger_event_id_ledger_events')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ledger_entries_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entries'))
    )
    op.create_index('ix_ledger_entries_house_user', 'ledger_entries', ['house_id', 'user_id'], unique=False)
    op.create_table('recurring_bills',
    sa.Column('house_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('rent', 'utilities', 'groceries', 'household', 'other', name='expense_category'), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('split_rule_id', sa.UUID(), nullable=False),
    sa.Column('paid_by', sa.UUID(), nullable=False),
    sa.Column('frequency', sa.Enum('weekly', 'fortnightly', 'monthly', name='bill_frequency'), nullable=False),
    sa.Column('anchor_day', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_paused', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], name=op.f('fk_recurring_bills_house_id_houses')),
    sa.ForeignKeyConstraint(['paid_by'], ['users.id'], name=op.f('fk_recurring_bills_paid_by_users')),
    sa.ForeignKeyConstraint(['split_rule_id'], ['split_rules.id'], name=op.f('fk_recurring_bills_split_rule_id_split_rules')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recurring_bills'))
    )
    op.create_table('expenses',
    sa.Column('house_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('paid_by', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('rent', 'utilities', 'groceries', 'household', 'other', name='expense_category'), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('split_rule_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('recurring_bill_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('active', 'reversed', name='expense_status'), server_default=sa.text("'active'"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_cents > 0', name=op.f('ck_expenses_amount_positive')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_expenses_created_by_users')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_expenses_document_id_documents')),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], name=op.f('fk_expenses_house_id_houses')),
    sa.ForeignKeyConstraint(['paid_by'], ['users.id'], name=op.f('fk_expenses_paid_by_users')),
    sa.ForeignKeyConstraint(['recurring_bill_id'], ['recurring_bills.id'], name=op.f('fk_expenses_recurring_bill_id_recurring_bills')),
    sa.ForeignKeyConstraint(['split_rule_id'], ['split_rules.id'], name=op.f('fk_expenses_split_rule_id_split_rules')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    op.create_table('disputes',
    sa.Column('house_id', sa.UUID(), nullable=False),
    sa.Column('expense_id', sa.UUID(), nullable=False),
    sa.Column('opened_by', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('open', 'under_review', 'resolved', 'rejected', name='dispute_status'), server_default=sa.text("'open'"), nullable=False),
    sa.Column('resolution_kind', sa.Enum('none', 'adjustment', 'full_reversal', name='resolution_kind'), server_default=sa.text("'none'"), nullable=False),
    sa.Column('resolution_event_id', sa.UUID(), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], name=op.f('fk_disputes_expense_id_expenses')),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], name=op.f('fk_disputes_house_id_houses')),
    sa.ForeignKeyConstraint(['opened_by'], ['users.id'], name=op.f('fk_disputes_opened_by_users')),
    sa.ForeignKeyConstraint(['resolution_event_id'], ['ledger_events.id'], name=op.f('fk_disputes_resolution_event_id_ledger_events')),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_disputes_resolved_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disputes'))
    )
    op.create_table('expense_shares',
    sa.Column('expense_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('share_cents', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], name=op.f('fk_expense_shares_expense_id_expenses')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_expense_shares_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expense_shares'))
    )
    op.create_table('dispute_comments',
    sa.Column('dispute_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_dispute_comments_author_id_users')),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], name=op.f('fk_dispute_comments_dispute_id_disputes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dispute_comments'))
    )
    # ### end Alembic commands ###

    # Integrity triggers (deferred to commit so multi-row events/shares can be
    # written incrementally within a transaction).
    op.execute("""
        CREATE FUNCTION check_ledger_event_zero_sum() RETURNS trigger AS $$
        DECLARE
            v_event_id uuid;
            v_sum bigint;
        BEGIN
            v_event_id := CASE WHEN TG_OP = 'DELETE'
                          THEN OLD.ledger_event_id ELSE NEW.ledger_event_id END;
            SELECT COALESCE(SUM(amount_cents), 0) INTO v_sum
            FROM ledger_entries WHERE ledger_event_id = v_event_id;
            IF v_sum <> 0 THEN
                RAISE EXCEPTION
                    'ledger event % entries sum to % (must be 0)', v_event_id, v_sum;
            END IF;
            RETURN NULL;
        END $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE CONSTRAINT TRIGGER trg_ledger_entries_zero_sum
        AFTER INSERT OR UPDATE OR DELETE ON ledger_entries
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW EXECUTE FUNCTION check_ledger_event_zero_sum();
    """)
    op.execute("""
        CREATE FUNCTION check_expense_shares_sum() RETURNS trigger AS $$
        DECLARE
            v_expense_id uuid;
            v_amount bigint;
            v_sum bigint;
        BEGIN
            v_expense_id := CASE WHEN TG_OP = 'DELETE'
                            THEN OLD.expense_id ELSE NEW.expense_id END;
            SELECT amount_cents INTO v_amount FROM expenses WHERE id = v_expense_id;
            SELECT COALESCE(SUM(share_cents), 0) INTO v_sum
            FROM expense_shares WHERE expense_id = v_expense_id;
            IF v_sum <> v_amount THEN
                RAISE EXCEPTION
                    'expense % shares sum to % (expected %)', v_expense_id, v_sum, v_amount;
            END IF;
            RETURN NULL;
        END $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE CONSTRAINT TRIGGER trg_expense_shares_sum
        AFTER INSERT OR UPDATE OR DELETE ON expense_shares
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW EXECUTE FUNCTION check_expense_shares_sum();
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # Triggers drop with their tables; functions must be dropped explicitly.
    op.execute("DROP TRIGGER IF EXISTS trg_expense_shares_sum ON expense_shares")
    op.execute("DROP TRIGGER IF EXISTS trg_ledger_entries_zero_sum ON ledger_entries")
    op.execute("DROP FUNCTION IF EXISTS check_expense_shares_sum()")
    op.execute("DROP FUNCTION IF EXISTS check_ledger_event_zero_sum()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dispute_comments')
    op.drop_table('expense_shares')
    op.drop_table('disputes')
    op.drop_table('expenses')
    op.drop_table('recurring_bills')
    op.drop_index('ix_ledger_entries_house_user', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_table('split_rules')
    op.drop_table('settlements')
    op.drop_table('notifications')
    op.drop_table('ledger_events')
    op.drop_table('idempotency_keys')
    op.drop_table('house_seq_counters')
    op.drop_table('house_memberships')
    op.drop_table('house_invites')
    op.drop_table('events')
    op.drop_table('documents')
    op.drop_table('balances')
    op.drop_table('users')
    op.drop_table('houses')
    # ### end Alembic commands ###

    # Enum types are not dropped by drop_table; migrations must be fully reversible.
    for enum_name in (
        'membership_role',
        'membership_status',
        'split_rule_kind',
        'expense_category',
        'expense_status',
        'ledger_event_kind',
        'settlement_status',
        'bill_frequency',
        'dispute_status',
        'resolution_kind',
        'document_status',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
    op.execute("DROP EXTENSION IF EXISTS citext")
