"""refresh tokens, nullable idempotency user

Revision ID: dbc8cc0f1165
Revises: 6862a82b142d
Create Date: 2026-07-11 12:21:49.966961

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dbc8cc0f1165'
down_revision: str | Sequence[str] | None = '6862a82b142d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('token_hash', name=op.f('pk_refresh_tokens'))
    )
    op.alter_column('idempotency_keys', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Rows for unauthenticated requests violate the restored NOT NULL; they are
    # 24h-TTL cache entries, safe to purge on downgrade.
    op.execute("DELETE FROM idempotency_keys WHERE user_id IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('idempotency_keys', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
